name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - development-deploy
      - production-deploy 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Ajusta según tu versión de Node.js

    - name: Install dependencies
      run: npm install

    - name: Determine Environment
      id: environment
      run: |
        if [[ "${{ github.ref_name }}" == "production-deploy" ]]; then
          echo "env=production" >> $GITHUB_ENV
          echo "ip=104.199.26.216" >> $GITHUB_ENV
        else
          echo "env=development" >> $GITHUB_ENV
          echo "ip=10.132.0.2" >> $GITHUB_ENV
        fi

    - name: Build Angular App
      run: |
        if [[ "${{ env.env }}" == "production" ]]; then
          npm run build-prod
        else
          npm run build-dev
        fi

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Add server to known_hosts
      run: |
        ssh-keyscan -H ${{ env.ip }} >> ~/.ssh/known_hosts

    - name: Transfer build files to VM
      run: |
        scp -r ./dist/todoapp dmarmijosa2667@${{ env.ip }}:/home/dmarmijosa2667/angular-app

    - name: Restart NGINX
      run: |
        ssh dmarmijosa2667@${{ env.ip }} "sudo systemctl restart nginx"